# Generated by Django 5.2.5 on 2025-10-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proposal',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='tenant',
        ),
    ]
