# Generated by Django 5.2.5 on 2025-10-13 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_clientcompany_logo'),
        ('proposal', '0002_alter_proposal_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='clients.clientcompany'),
        ),
    ]
