# Generated by Django 5.2.5 on 2025-10-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_proposal_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
