# Generated by Django 5.2.5 on 2025-10-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0004_proposal_deleted_at_proposal_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalitem',
            name='hsn_sac_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='part_service_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='template',
            field=models.IntegerField(choices=[(1, 'Classic'), (2, 'Modern'), (3, 'Professional'), (6, 'Your Custom Template')], default=1),
        ),
    ]
