# Generated by Django 5.2.5 on 2025-09-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_email_otp_code_user_email_otp_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
