# Generated by Django 5.2.5 on 2025-10-15 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_amount_remove_proposal_amount_and_more'),
        ('proposal', '0003_proposal_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='proposal.proposal'),
        ),
        migrations.DeleteModel(
            name='ProposalItem',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
    ]
