# Generated by Django 5.2.5 on 2025-10-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_proposal_tenant_alter_invoice_proposal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tenant',
        ),
    ]
