# Generated by Django 5.2.5 on 2025-10-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_invoice_tenant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
