# Generated by Django 5.2.5 on 2025-10-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_deleted_at_invoice_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='hsn_sac',
            field=models.CharField(blank=True, max_length=50, verbose_name='HSN/SAC Code'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='part_service_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Part/Service Code'),
        ),
    ]
