# Generated by Django 5.2.5 on 2025-10-17 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0006_delete_receipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('client_name', models.CharField(default='Unknown Client', max_length=255)),
                ('client_email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField(blank=True, default=None, null=True)),
                ('next_payment', models.DateField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Partially Paid', 'Partially Paid'), ('Paid', 'Paid'), ('Closed', 'Closed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['receipt_number'], name='receipts_re_receipt_840679_idx'), models.Index(fields=['status'], name='receipts_re_status_ce247e_idx'), models.Index(fields=['created_at'], name='receipts_re_created_f612f6_idx')],
            },
        ),
    ]
