# Generated by Django 5.2.5 on 2025-10-17 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='receipt',
            name='receipts_re_receipt_840679_idx',
        ),
    ]
