# Generated by Django 5.2.5 on 2025-10-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_remove_receipt_receipts_re_receipt_840679_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
