# Generated by Django 5.2.5 on 2025-10-18 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_alter_receipt_receipt_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
