# Generated by Django 5.2.5 on 2025-09-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientcompany',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='clientcompany',
            name='tenant',
        ),
    ]
