# Generated by Django 5.2.5 on 2025-09-13 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clientcompany_unique_together_and_more'),
        ('tenants', '0003_tenant_is_active_tenant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcompany',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_companies', to='tenants.tenant'),
        ),
    ]
