<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-09-15 06:05
=======
# Generated by Django 5.2.5 on 2025-09-15 12:29
>>>>>>> c46c08493304a5a51e9bda6fcc65b57df034a26c

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientcompany_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcompany',
            name='tenant',
        ),
    ]
