# Generated by Django 5.2.5 on 2025-09-15 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_clientcompany_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcompany',
            name='tenant',
        ),
    ]
