# Generated by Django 5.2.5 on 2025-09-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_clientcompany_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcompany',
            name='account_manager',
        ),
    ]
