# Generated by Django 5.2.5 on 2025-09-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_remove_clientcompany_account_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcompany',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
