# Generated by Django 5.2.5 on 2025-09-27 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_clientcompany_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/logos/'),
        ),
    ]
