# Generated by Django 5.2.5 on 2025-09-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_clientcompany_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcompany',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='uploads/logos/'),
        ),
    ]
