# Generated by Django 5.2.5 on 2025-10-22 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='user',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
