# Generated by Django 5.2.5 on 2025-09-16 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productservices', '0001_initial'),
        ('tenants', '0003_tenant_is_active_tenant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tenants.tenant'),
        ),
    ]
