# Generated by Django 5.2.5 on 2025-09-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productservices', '0002_category_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tenant',
        ),
    ]
