# Generated by Django 5.2.5 on 2025-09-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productservices', '0003_remove_category_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productservice',
            name='entrepreneur',
        ),
        migrations.AddField(
            model_name='productservice',
            name='entrepreneur_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
