# Generated by Django 5.2.5 on 2025-09-17 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productservices', '0004_remove_productservice_entrepreneur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productservice',
            name='entrepreneur_id',
        ),
    ]
