# Generated by Django 5.2.5 on 2025-10-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productservices', '0005_remove_productservice_entrepreneur_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productservice',
            name='sku',
        ),
        migrations.AddField(
            model_name='productservice',
            name='HSN_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
