# Generated by Django 5.2.5 on 2025-10-11 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productservices', '0006_remove_productservice_sku_productservice_hsn_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productservice',
            old_name='HSN_code',
            new_name='hsn_code',
        ),
    ]
