# Generated by Django 5.2.5 on 2025-10-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productservices', '0007_rename_hsn_code_productservice_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productservice',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='HSN Code'),
        ),
    ]
