# Generated by Django 5.2.5 on 2025-10-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonenquiry',
            name='mobile',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
